### ISSUE TITLE
JitPack link 404s

### ISSUE THREAD

**Issue by james-otten** [frohoff/ysoserial#89]
The JitPack link in `README.md` 404s. The [directory](https://jitpack.io/com/github/frohoff/ysoserial/master/) seems to be there, and I see [logs](https://jitpack.io/com/github/frohoff/ysoserial/master/build.log), but the artifact does not appear to be available. There are a couple warnings in the build log I looked at, but at the end it does list the artifact, so it would seem that it was created.

Link:
`https://jitpack.io/com/github/frohoff/ysoserial/master/ysoserial-master.jar`

To test:
```
user@localhost:~$ curl https://jitpack.io/com/github/frohoff/ysoserial/master/ysoserial-master.jar
Build failed. See the log at jitpack.io
```

**Comment by frohoff** [comment]
Thanks for reporting. Link should be working again.

**Comment by james-otten** [comment]
@frohoff would you mind trying again? I'm still seeing the same thing.

**Comment by frohoff** [comment]
Seems to work for me. Maybe geolocation-dependent CDN cache problem?

```console
curl -sv https://jitpack.io/com/github/frohoff/ysoserial/master/ysoserial-master.jar 2> >(grep HTTP/ >&2) | file -
> GET /com/github/frohoff/ysoserial/master/ysoserial-master.jar HTTP/2
< HTTP/2 200 
/dev/stdin: Zip archive data, at least v1.0 to extract
```

**Comment by Selvayen** [comment]
I am also having the same issue.  The link says the build failed and the file doesn't exist in the directory listing.

**Comment by Selvayen** [comment]
@frohoff I am also having the same issue. The link says the build failed and the file doesn't exist in the directory listing.

**Comment by frohoff** [comment]
Still works for me but I can see from https://www.uptrends.com/tools/uptime that it seems to be returning a 404. 

![img](https://i.imgur.com/R49FOGj.png)

Wonder if it could be a CDN cache problem. I'll see what I can do.

**Comment by frohoff** [comment]
Can you tell me what is in this log file when you view/download? https://jitpack.io/com/github/frohoff/ysoserial/master/build.log

**Comment by Selvayen** [comment]
Looks like a successful build for 0.0.6 using mvn that is timestamped from 1-30-2018.  What specific information do you need for me to look for?

**Comment by frohoff** [comment]
Just wanted to confirm that the log was 1) being served successfully and 2) showed a successful build in the problem areas. I'm guessing it's a CDN cache issue with the specific jar file.

**Comment by frohoff** [comment]
Can you try this different link? The uptrends.com service shows it as successfully served in all but a couple locales.

https://jitpack.io/com/github/frohoff/ysoserial/master-SNAPSHOT/ysoserial-master-SNAPSHOT.jar

**Comment by Selvayen** [comment]
That link works.  I appreciate the quick response/fix!

**Comment by frohoff** [comment]
No problem. I just remembered having a similar issue a few months ago that caused me to [switch from `master-SNAPSHOT` to `master`](https://github.com/frohoff/ysoserial/commit/e9f112ac50ef4fad5a5858068162cc6987cf9121#diff-04c6e90faac2675aa89e2176d2eec7d8), so I'll need to keep an eye on it.
